services: 
  financial-app-frontend:
    build: .
    image: financial-app:latest
    container_name: financial-app
    ports:
      - "5173:5173"
    command: npm run prod -- --host 0.0.0.0
    env_file:
      - ./.env.production