services: 
  financial-app-frontend:
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300 



